### ISSUE TITLE
Messages in Group Chats Not Sent

### ISSUE THREAD

**Issue by cwmke** [kfatehi/matrix-puppet-imessage#31]
I am able to receive group messages but not reply. Single person to person messages work as expected. This occurred with two separate group messages with all users using imessage not mms. The below error shows up in Terminal. Thanks for any help you provide!

MacOS: 10.13.6

````
full applescript tell application "Messages"
    activate
    set budy0 to first buddy whose handle is "=2b<FIRSTNUMBER>"
        set buddy1 to first buddy whose handle is "=2b1<SECONDNUMBER>"
    set thisChat to make new text chat with properties {participants:{buddy0,buddy1}}
    send "<MESSAGE CONTENT> " to thisChat
  end tell
59:103: execution error: Messages got an error: Can't get buddy 1 whose handle =  "=2b<FIRSTNUMBER>". Invalid index. (-1719)
sendEvent of type m.room.message in !<ROOM>:website.net with m1234567890123.1
Event set to !<ROOM>:website.net with event id $<EVENTID>
`````

```
Error in handleMatrixEvent { Error: exited nonzero
    at ChildProcess. (/Users/USERNAME/matrix-puppet-imessage/src/imessage-send-group.js:49:18)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  [stack]:
   'Error: exited nonzero\n    at ChildProcess. (/Users/USERNAME/matrix-puppet-imessage/src/imessage-send-group.js:49:18)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)',
  [message]: 'exited nonzero' } { age: 33,
  content:
   { body:
      'MESSAGE',
     msgtype: 'm.text' },
  event_id: '$kvKsRcxp8W44kwn_W5BwElx4F9fjPsDbkWkNH_aJLQ',
  origin_server_ts: 1111111111111,
  room_id: '!VEdCCGuqmEccwednBS:hostname.net',
  sender: '@<username>:hostname.net',
  type: 'm.room.message',
  unsigned: { age: 33 },
  user_id: '@<username>:hostname.net',
  getRoomId: { [Function] [length]: 0, [name]: '' },
  getId: { [Function] [length]: 0, [name]: '' } } ﻿
```

**Comment by cvincent** [comment]
I get the same thing, same macOS version. I've held back from updating specifically because in the past I've run my own front-end, uMessage (https://github.com/cvincent/umessage), and heard there were some breaking changes to the AppleScript API in later versions. I haven't confirmed this, but avoided updating to be safe. And then group messaging stopped working in uMessage seemingly out of nowhere, which is part of why I've decided to try Matrix with this bridge.

Can anyone confirm if the bridge works with newer versions of macOS? If so, I can try upgrading. Willing to contribute to the project as I have some knowledge from working on uMessage that might be helpful.

**Comment by cwmke** [comment]
```
Error in handleMatrixEvent { Error: exited nonzero
    at ChildProcess. (/Users/USERNAME/matrix-puppet-imessage/src/imessage-send-group.js:49:18)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  [stack]:
   'Error: exited nonzero\n    at ChildProcess. (/Users/USERNAME/matrix-puppet-imessage/src/imessage-send-group.js:49:18)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)',
  [message]: 'exited nonzero' } { age: 33,
  content:
   { body:
      'MESSAGE',
     msgtype: 'm.text' },
  event_id: '$kvKsRcxp8W44kwn_W5BwElx4F9fjPsDbkWkNH_aJLQ',
  origin_server_ts: 1111111111111,
  room_id: '!VEdCCGuqmEccwednBS:hostname.net',
  sender: '@<username>:hostname.net',
  type: 'm.room.message',
  unsigned: { age: 33 },
  user_id: '@<username>:hostname.net',
  getRoomId: { [Function] [length]: 0, [name]: '' },
  getId: { [Function] [length]: 0, [name]: '' } } ﻿
```
