### ISSUE TITLE
No incoming messages received

### ISSUE THREAD

**Issue by allquixotic** [kfatehi/matrix-puppet-imessage#33]
On Mojave point release .6 and Matrix Synapse latest-py3 as of today (from Dockerhub)... I don't receive iMessages from others, but they can get my messages. This is a Matrix side problem, not an iMessage side problem.

```
Unhandled rejection Error: Failed to join room
    at /Users/sean/matrix-puppet-imessage/node_modules/matrix-appservice-bridge/lib/components/intent.js:725:53
    at tryCatcher (/Users/sean/matrix-puppet-imessage/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sean/matrix-puppet-imessage/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/sean/matrix-puppet-imessage/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:604:18)
```

The UI symptom: in Riot, the third party's "user" who would join the DM room with me, never actually joins the room. The iMessage bot leaves the room shortly after it's created.

Oddly, when I message myself, it works in both directions.

**Comment by bijeebuss** [comment]
Did you ever figure out what the issue was. Mine isn't working at all but I don't see any errors

**Comment by allquixotic** [comment]
Now I am getting correct messages received, but I can't send. It looks like we can't receive messages from email addresses, only from phone numbers or known contacts.

Still not sure why send isn't working.

**Comment by elmehalawi** [comment]
@allquixotic Did you ever figure that one out? I'm having that same problem: I can receive iMessages, but I can't send them.
